### ISSUE TITLE
move these files into the ONIE repo ??

### ISSUE THREAD

**Issue by cbrune** [bluejumper/build-onie#2]
Hello @bluejumper -

I think what you have done is *really* great.  Various folks have wanted this for a long time, but no one ever stood up and made it happen.  Honestly, thanks a bunch for doing this.

I have a couple of suggestions, however.

First off I think we should move this into the ONIE repo proper.  We have a top level `contrib` sub-directory which could house this code nicely.  Longer term I think it will be easier to maintain this code if it lives alongside the main ONIE code base.  Also the ONIE documentation could more easily refer to this code.

My other suggestions are in the nature of polish, minor things really.  For example instead of having the big `apt-get install ...` happen when the docker image is created, I would move that step to the instructions and just have the end user run `make debian-prepare-build-host`.  The list of packages needed on the build host does change a little of over time, so relying on `make debian-prepare-build-host` will prevent us from having to maintain two separate, but nearly identical lists of packages.  Anyway that is just a polishing suggestion.

If you are agreeable to me relocating your code let me know.  I can make the ONIE pull requests and update various ONIE wiki documentation.  I know your LICENSE terms already allow me to do this, but I'd like to include your input first.

Cheers,
Curt

**Comment by bluejumper** [comment]
Hello cbrune,

I'm very open to including this Dockerfile within the ONIE repository. A tool like Docker and this file should improve the build process for a lot of users, and would greatly reduce the difficulty and time needed to deliver a successful software build. It _should_ be in the hands of the developers involved with ONIE. And they are very welcome to suggest and improve upon these tools. By no means am I an expert, and so I am humbled to have the opportunity to review a contribution.

You raise a very good point about using `make debian-prepare-build-host`. It was where I obtained the dependency information and I was unaware that it was to be used as a _make_ procedure. Aha!

I would raise a question of whether one would like the dependencies included within the container. There are two perfectly valid ways of approaching a primed build environment: a ready-to-order Makefile or a factory-made Dockerfile. A container can be expected to include dependencies. In fact, it is possible for the Dockerfile to rely on the same dependency list as Makefile.

I will offer a solution in a future commit, I'll add better polish :smile: In the meantime, you have the freedom to pop this in the ONIE repository. I could show my folks at home when it's done!

Many regards!
Benayak
